// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package LogGroup

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LogContent struct {
	_tab flatbuffers.Table
}

func GetRootAsLogContent(buf []byte, offset flatbuffers.UOffsetT) *LogContent {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LogContent{}
	x.Init(buf, n+offset)
	return x
}

func FinishLogContentBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsLogContent(buf []byte, offset flatbuffers.UOffsetT) *LogContent {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &LogContent{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedLogContentBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *LogContent) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LogContent) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *LogContent) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *LogContent) Value() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func LogContentStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func LogContentAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(key), 0)
}
func LogContentAddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(value), 0)
}
func LogContentEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
