// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package LogGroup

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LogTag struct {
	_tab flatbuffers.Table
}

func GetRootAsLogTag(buf []byte, offset flatbuffers.UOffsetT) *LogTag {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LogTag{}
	x.Init(buf, n+offset)
	return x
}

func FinishLogTagBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsLogTag(buf []byte, offset flatbuffers.UOffsetT) *LogTag {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &LogTag{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedLogTagBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *LogTag) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LogTag) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *LogTag) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *LogTag) Value() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func LogTagStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func LogTagAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(key), 0)
}
func LogTagAddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(value), 0)
}
func LogTagEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
